// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterDuner.Cooperations.Csq.Channels.Generators
{
    using System;
    using MasterDuner.Cooperations.Csq.Commons;
    
    
    #line 1 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    internal partial class SearchRequirementUrlGenerator : SearchRequirementUrlGeneratorBase
    {
        private HPRequirement _searchParameter;
        private ResultPage _page;

        internal HPRequirement SearchParameter
        {
            get { return _searchParameter; }
            set { _searchParameter = value; }
        }

        internal ResultPage Page
        {
            get { return _page; }
            set { _page = value; }
        }

        internal virtual string TransformText()
        {
            this.Write("Q=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetKeywords()));
            
            #line default
            #line hidden
            this.Write("&CompanyName=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetCorporationName()));
            
            #line default
            #line hidden
            this.Write("&IsArecent=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWhetherLastestMark().ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("&CompanyIndustry=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetIndustriesStr()));
            
            #line default
            #line hidden
            this.Write("&JobType=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetJobTypeStr()));
            
            #line default
            #line hidden
            this.Write("&JobLocation=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetResidencesStr()));
            
            #line default
            #line hidden
            this.Write("&DesiredWorkLocation=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWorkLocationStr()));
            
            #line default
            #line hidden
            this.Write("&WorkStatus=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWorkingStatus()));
            
            #line default
            #line hidden
            this.Write("&Gender=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetGender()));
            
            #line default
            #line hidden
            this.Write("&AgeMin=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetAgeSegment().Lower));
            
            #line default
            #line hidden
            this.Write("&AgeMax=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetAgeSegment().Upper));
            
            #line default
            #line hidden
            this.Write("&WorkExperienceMin=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWorkExperienceSegment().Lower));
            
            #line default
            #line hidden
            this.Write("&WorkExperienceMax=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWorkExperienceSegment().Upper));
            
            #line default
            #line hidden
            this.Write("&AdegreeMin=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetMinDegreeID()));
            
            #line default
            #line hidden
            this.Write("&AdegreeMax=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetMaxDegreeID()));
            
            #line default
            #line hidden
            this.Write("&SchoolName=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetSchoolName()));
            
            #line default
            #line hidden
            this.Write("&ProfessionalTitle=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetProfessionName()));
            
            #line default
            #line hidden
            this.Write("&");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetLanguageAbilityStr()));
            
            #line default
            #line hidden
            this.Write("&OverseasJobExperience=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetWhetherIncludeOverseasMark()));
            
            #line default
            #line hidden
            this.Write("&ResumeID=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchParameter.GetResumeNumber()));
            
            #line default
            #line hidden
            this.Write("&PageIndex=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Page.Index));
            
            #line default
            #line hidden
            this.Write("&PageSize=");
            
            #line 2 "E:\CSharp\Customizations\人力资源管理系统\CSQ 2.x\Csq.Channels.HighpinCn\Generators\SearchRequirementUrlGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Page.Size));
            
            #line default
            #line hidden
            this.Write("&Sort=LastUpTime+desc&IsAbstract=true\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    internal class SearchRequirementUrlGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        internal System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        internal string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        internal virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        internal void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        internal void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        internal void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        internal void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        internal void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        internal void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        internal void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        internal string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        internal void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        internal class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            internal System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            internal string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        internal ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
