//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace MasterDuner.Cooperations.Csq.TestProjects.HPParserService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HPPrivateServiceSoap", Namespace="urn:MasterDuner@Yeah.net")]
    public partial class HPPrivateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ParseTheSearchResultHtmlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HPPrivateService() {
            this.Url = global::MasterDuner.Cooperations.Csq.TestProjects.Properties.Settings.Default.demo_HPParserService_HPPrivateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ParseTheSearchResultHtmlCompletedEventHandler ParseTheSearchResultHtmlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:MasterDuner@Yeah.net/ParseTheSearchResultHtml", RequestNamespace="urn:MasterDuner@Yeah.net", ResponseNamespace="urn:MasterDuner@Yeah.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResultObject[] ParseTheSearchResultHtml(string html) {
            object[] results = this.Invoke("ParseTheSearchResultHtml", new object[] {
                        html});
            return ((SearchResultObject[])(results[0]));
        }
        
        /// <remarks/>
        public void ParseTheSearchResultHtmlAsync(string html) {
            this.ParseTheSearchResultHtmlAsync(html, null);
        }
        
        /// <remarks/>
        public void ParseTheSearchResultHtmlAsync(string html, object userState) {
            if ((this.ParseTheSearchResultHtmlOperationCompleted == null)) {
                this.ParseTheSearchResultHtmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParseTheSearchResultHtmlOperationCompleted);
            }
            this.InvokeAsync("ParseTheSearchResultHtml", new object[] {
                        html}, this.ParseTheSearchResultHtmlOperationCompleted, userState);
        }
        
        private void OnParseTheSearchResultHtmlOperationCompleted(object arg) {
            if ((this.ParseTheSearchResultHtmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParseTheSearchResultHtmlCompleted(this, new ParseTheSearchResultHtmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:MasterDuner@Yeah.net")]
    public partial class SearchResultObject {
        
        private bool isMatchField;
        
        private string positionNameField;
        
        private string resumeDetailsUrlField;
        
        private string corporationNameField;
        
        private string genderField;
        
        private int ageField;
        
        private string degreeNameField;
        
        private string residenceField;
        
        private string educationalBackgroundField;
        
        private string workingExperienceField;
        
        private string[] resumeTagsField;
        
        private string pictureUrlField;
        
        /// <remarks/>
        public bool IsMatch {
            get {
                return this.isMatchField;
            }
            set {
                this.isMatchField = value;
            }
        }
        
        /// <remarks/>
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
            }
        }
        
        /// <remarks/>
        public string ResumeDetailsUrl {
            get {
                return this.resumeDetailsUrlField;
            }
            set {
                this.resumeDetailsUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CorporationName {
            get {
                return this.corporationNameField;
            }
            set {
                this.corporationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string DegreeName {
            get {
                return this.degreeNameField;
            }
            set {
                this.degreeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Residence {
            get {
                return this.residenceField;
            }
            set {
                this.residenceField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalBackground {
            get {
                return this.educationalBackgroundField;
            }
            set {
                this.educationalBackgroundField = value;
            }
        }
        
        /// <remarks/>
        public string WorkingExperience {
            get {
                return this.workingExperienceField;
            }
            set {
                this.workingExperienceField = value;
            }
        }
        
        /// <remarks/>
        public string[] ResumeTags {
            get {
                return this.resumeTagsField;
            }
            set {
                this.resumeTagsField = value;
            }
        }
        
        /// <remarks/>
        public string PictureUrl {
            get {
                return this.pictureUrlField;
            }
            set {
                this.pictureUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ParseTheSearchResultHtmlCompletedEventHandler(object sender, ParseTheSearchResultHtmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParseTheSearchResultHtmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParseTheSearchResultHtmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResultObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResultObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591