//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace ZpDemo.WsReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HighpinCnWsiSoap", Namespace="http://www.highpin.cn")]
    public partial class HighpinCnWsi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestSessionTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformFirstStepOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestValidatingCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HighpinCnWsi() {
            this.Url = global::ZpDemo.Properties.Settings.Default.ZpDemo_WsReference_HighpinCnWsi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestSessionTagCompletedEventHandler RequestSessionTagCompleted;
        
        /// <remarks/>
        public event PerformFirstStepCompletedEventHandler PerformFirstStepCompleted;
        
        /// <remarks/>
        public event RequestValidatingCodeCompletedEventHandler RequestValidatingCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.highpin.cn/RequestSessionTag", RequestNamespace="http://www.highpin.cn", ResponseNamespace="http://www.highpin.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientSessionTag RequestSessionTag() {
            object[] results = this.Invoke("RequestSessionTag", new object[0]);
            return ((ClientSessionTag)(results[0]));
        }
        
        /// <remarks/>
        public void RequestSessionTagAsync() {
            this.RequestSessionTagAsync(null);
        }
        
        /// <remarks/>
        public void RequestSessionTagAsync(object userState) {
            if ((this.RequestSessionTagOperationCompleted == null)) {
                this.RequestSessionTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestSessionTagOperationCompleted);
            }
            this.InvokeAsync("RequestSessionTag", new object[0], this.RequestSessionTagOperationCompleted, userState);
        }
        
        private void OnRequestSessionTagOperationCompleted(object arg) {
            if ((this.RequestSessionTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestSessionTagCompleted(this, new RequestSessionTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.highpin.cn/PerformFirstStep", RequestNamespace="http://www.highpin.cn", ResponseNamespace="http://www.highpin.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformFirstStep(ClientSessionTag sessionTag) {
            object[] results = this.Invoke("PerformFirstStep", new object[] {
                        sessionTag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PerformFirstStepAsync(ClientSessionTag sessionTag) {
            this.PerformFirstStepAsync(sessionTag, null);
        }
        
        /// <remarks/>
        public void PerformFirstStepAsync(ClientSessionTag sessionTag, object userState) {
            if ((this.PerformFirstStepOperationCompleted == null)) {
                this.PerformFirstStepOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformFirstStepOperationCompleted);
            }
            this.InvokeAsync("PerformFirstStep", new object[] {
                        sessionTag}, this.PerformFirstStepOperationCompleted, userState);
        }
        
        private void OnPerformFirstStepOperationCompleted(object arg) {
            if ((this.PerformFirstStepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformFirstStepCompleted(this, new PerformFirstStepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.highpin.cn/RequestValidatingCode", RequestNamespace="http://www.highpin.cn", ResponseNamespace="http://www.highpin.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RequestValidatingCode(ClientSessionTag sessionTag) {
            object[] results = this.Invoke("RequestValidatingCode", new object[] {
                        sessionTag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RequestValidatingCodeAsync(ClientSessionTag sessionTag) {
            this.RequestValidatingCodeAsync(sessionTag, null);
        }
        
        /// <remarks/>
        public void RequestValidatingCodeAsync(ClientSessionTag sessionTag, object userState) {
            if ((this.RequestValidatingCodeOperationCompleted == null)) {
                this.RequestValidatingCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestValidatingCodeOperationCompleted);
            }
            this.InvokeAsync("RequestValidatingCode", new object[] {
                        sessionTag}, this.RequestValidatingCodeOperationCompleted, userState);
        }
        
        private void OnRequestValidatingCodeOperationCompleted(object arg) {
            if ((this.RequestValidatingCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestValidatingCodeCompleted(this, new RequestValidatingCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.highpin.cn")]
    public partial class ClientSessionTag {
        
        private System.Guid sessionIdField;
        
        /// <remarks/>
        public System.Guid SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RequestSessionTagCompletedEventHandler(object sender, RequestSessionTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestSessionTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestSessionTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientSessionTag Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientSessionTag)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PerformFirstStepCompletedEventHandler(object sender, PerformFirstStepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformFirstStepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformFirstStepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RequestValidatingCodeCompletedEventHandler(object sender, RequestValidatingCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestValidatingCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestValidatingCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591