//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDuner.Cooperations.Csq.Channels.Configuration
{
    
    
    /// <summary>
    /// 智联卓聘网页面URL配置。
    /// </summary>
    public sealed partial class HPActionUrlElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets 设置或获取URL标识名称。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取URL标识名称。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Name
        {
            get
            {
                return ((string)(base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.NamePropertyName]));
            }
            set
            {
                base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region BaseUrl Property
        /// <summary>
        /// The XML name of the <see cref="BaseUrl"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string BaseUrlPropertyName = "baseUrl";
        
        /// <summary>
        /// Gets or sets 设置或获取基础URL。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取基础URL。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.BaseUrlPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string BaseUrl
        {
            get
            {
                return ((string)(base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.BaseUrlPropertyName]));
            }
            set
            {
                base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement.BaseUrlPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace MasterDuner.Cooperations.Csq.Channels.Configuration
{
    
    
    /// <summary>
    /// HPActionUrlElement配置集合。
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMap, AddItemName=global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElementCollection.HPActionUrlElementPropertyName)]
    public sealed partial class HPActionUrlElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string HPActionUrlElementPropertyName = "add";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMap;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElementCollection.HPActionUrlElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElementCollection.HPActionUrlElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement this[int index]
        {
            get
            {
                return ((global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement this[object name]
        {
            get
            {
                return ((global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace MasterDuner.Cooperations.Csq.Channels.Configuration
{
    
    
    /// <summary>
    /// 智联卓聘网私有配置。
    /// </summary>
    public sealed partial class HPSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ActionUrls Property
        /// <summary>
        /// The XML name of the <see cref="ActionUrls"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ActionUrlsPropertyName = "actionUrls";
        
        /// <summary>
        /// Gets or sets 设置或获取智联卓聘网的URL配置。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("设置或获取智联卓聘网的URL配置。")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPSection.ActionUrlsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElementCollection ActionUrls
        {
            get
            {
                return ((global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPActionUrlElementCollection)(base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPSection.ActionUrlsPropertyName]));
            }
            set
            {
                base[global::MasterDuner.Cooperations.Csq.Channels.Configuration.HPSection.ActionUrlsPropertyName] = value;
            }
        }
        #endregion
    }
}
